# Generated by Django 5.2 on 2025-04-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pace', models.FloatField()),
                ('shooting', models.FloatField()),
                ('passing', models.FloatField()),
                ('dribbling', models.FloatField()),
                ('defending', models.FloatField()),
                ('physic', models.FloatField()),
                ('prediction', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
